import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The sprite sheet itself is generated by `node scripts/compose-avatars.mjs`
 * (needs ImageMagick) and committed as base64 so a plain `npm ci && build`
 * on CI can produce the binary asset without any image tooling.
 */
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, "src/assets/legends-avatars.b64");
const output = resolve(root, "public/avatars/legends.webp");

const base64 = (await readFile(source, "utf8")).replace(/\s+/g, "");
await mkdir(dirname(output), { recursive: true });
await writeFile(output, Buffer.from(base64, "base64"));
console.log("✓ Legend avatar sprite generated.");
